### ISSUE TITLE
'.' doesnot popup omni-menus in python omnicomplete 

### ISSUE THREAD

**Issue by wining** [lifepillar/vim-mucomplete#105]
![a](https://user-images.githubusercontent.com/4005513/42143360-3c4ce268-7de7-11e8-80c2-2a88bfc214c3.gif)
as in the gif,
 if 'os' already typed, then '.' will popups omni complete menus,
but the 'os.' popups only the key complete menus.
my config:
```vim
let g:mucomplete#can_complete.python = { 'omni': { t -> t =~# '\m\k\%(\k\|\.\)$' } }
```

**Comment by lifepillar** [comment]
That is an issue with Python completion, I'd say. To verify that, turn off MUcomplete with `:MUcompleteAutoOff`, then type: `os<c-x><c-o>`. A menu showing only one `os` entry should appear (not aligned with the word, btw). Then, type `.`: nothing happens and the menu stays open. IMO, the right behaviour is that the menu should close after typing `.`, because there is no match.

A workaround is as follows: after typing `os.`, press CTRL-J or CTRL-H to cycle through the completion methods. This will re-trigger omni-completion and you should get the right completions.

Another option is to try some Python plugin using a different completion function, such as jedi-vim.
