### ISSUE TITLE
Do not suggest while in string

### ISSUE THREAD

**Issue by midnio** [lifepillar/vim-mucomplete#121]
I was trying to record a review of mucomplete because it's my favorite completion plugin now and while I'm trying to record the review, i see it suggests clojure functions inside strings. There is my recorded preview:

[![asciicast](https://asciinema.org/a/0VjbHwNFqHHX9pzpk56Cxjkl1.png)](https://asciinema.org/a/0VjbHwNFqHHX9pzpk56Cxjkl1)

After solve this bug, i'll record one more preview and send it to twitter :p

**Comment by lifepillar** [comment]
I am not familiar with clojure. Can you provide an example? (The link to the screencast is broken: you've likely pasted a non-public link).

**Comment by midnio** [comment]
https://www.dropbox.com/s/odsz4tl6f9avvqk/simplescreenrecorder-2018-09-01_21.47.44.mkv?dl=0

This is the dropbox link I recorded later. When I write function names outside string it works fine. But why I say a function name in the string, it shows the menu already. Is this a feature, or bug?

**Comment by lifepillar** [comment]
>Is this a feature, or bug?

By default, MUcomplete uses a fairly liberal condition to decide whether omni-completion should be fired or not: it's enough to have one or two keyword characters in front of the cursor. This condition may be overridden by the user for each filetype in a flexible way. 

Whether omni-completion should be triggered inside strings or not is mostly a user's preference, I'd say (I can certainly think of cases in which I do want that). Checking whether the user is typing inside a string can be tricky and/or inefficient. So, MUcomplete leans on the side on simplicity, leaving the user the possibility to do something more complicated. In this case, putting this your `vimrc` should work, although possibly not very efficiently:

```vim
let g:mucomplete#can_complete = {}
let s:clojure_cond = { t -> t =~# '\m\k\k$' &&
    \ synIDattr(synID(line("."), col(".") - 1, 0), "name") != 'clojureString' }
let g:mucomplete#can_complete.clojure = { 'omni': s:clojure_cond }
```

**Comment by mg979** [comment]
I added this feature to my fork in the [c-space branch](https://github.com/mg979/vim-mucomplete/tree/c-space), that includes also another feature. @lifepillar can take a look if he wants.

[Here](https://github.com/mg979/vim-mucomplete/blob/def0c8d38eaa2e0a4fc018c982c55276fc418c34/doc/mucomplete.txt#L447) are the instruction for scoped chains (and possibly exclusions).

Another feature added there, is switching to alternate completion chains with `ctrl-space`, so that you can have a similar behaviour as in YouCompleteMe, where `ctrl-space` enables semantic completion (but here you can choose the completion types). Instructions [just above](https://github.com/mg979/vim-mucomplete/blob/def0c8d38eaa2e0a4fc018c982c55276fc418c34/doc/mucomplete.txt#L437).
