### ISSUE TITLE
Different completion chains for <s-Tab> and <Tab>

### ISSUE THREAD

**Issue by tripurari001** [lifepillar/vim-mucomplete#147]
Hi 
I was just wondering if I can define different completion chain for `shitf+tab`

for example I want to use `c-n` for `Tab` and `c-p` for `shift+Tab`
is this possible ?

Thanks

**Comment by lifepillar** [comment]
Shift-Tab is used to traverse the completion chain backwards, so if you set your completion chain as `['c-n', 'c-p']`, `c-n` is tried first when using Tab and `c-p` is tried first when using Shift-Tab. So, for your example that should work as you expect, because if one method fails, the other should fail, too (IIRC how CTRL-N and CTRL-P work), so there no fallback in practice.

But in general, you cannot define two distinct completion chains and map them to different keys. I don't know how common a scenario that is: after all, the purpose of MUcomplete is to aggregate different methods under a single keystroke.

**Comment by tripurari001** [comment]
Cool Thanks for help
That works for me
