### ISSUE TITLE
My setup only pick up words from the current file and nothing else

### ISSUE THREAD

**Issue by mottalrd** [lifepillar/vim-mucomplete#149]
Hello, thank you for this awesome plugin

Unfortunately my setup doesn't seem to pick up keywords from other files.
This is what I got:
```
set completeopt+=menuone
set completeopt+=noselect
set shortmess+=c   " Shut off completion messages
let g:mucomplete#enable_auto_at_startup = 1
```

When I turn off mucomplete and I use the normal Ctrl+P built in VIM mechanism I do get suggestions from other files so I am assuming I must enable something on mucomplete to make that happen.

What am I doing wrong?
Thank you for your help

**Comment by lifepillar** [comment]
By default, MUComplete uses only buffer keyword completion (`'keyn'` method). You need to define your own completion chain. Add this to your `vimrc`:

```vim
let g:mucomplete#chains = { 'default': ['path', 'omni', 'c-p', 'dict', 'uspl'] }
```

This replaces `'keyn'` with `'c-p'` in the default completion chain. Of course, you may use whatever methods you like. For instance, if you need only path completion and Ctrl+P, use:

```vim
let g:mucomplete#chains = { 'default': ['path', 'c-p'] }
```

You may want to read (at least) `:help mucomplete-methods` and `:help mucomplete-chains`.

**Comment by lifepillar** [comment]
Keep in mind that completion with Ctrl+p (`'c-p'` method in MUcomplete) may become slow if there are many files to search. If you insist in keeping autocompletion on, typing may become too slow. If that happens, *Optimize your completion chains* in `:help mucomplete-tips` may help. You may also keep autocompletion on, but activate `'c-p'` completion only when pressing Tab. That's also explained in the documentation.

**Comment by mg979** [comment]
I think the problem is that `<c-p>` is used to cycle the current popup item backwards, so if you use `g:mucomplete#enable_auto_at_startup`, it can't be used to do what you want, because you must close the popup first.

You could do:

* press `<c-e><c-p>` if popup if visible, so that you dismiss the previous popup 
* use another key for `<c-p>` completion, like:
```vim
inoremap <expr> <c-b> pumvisible() ? "\<c-g>\<c-g>\<c-p>" : "\<c-p>"
```

Both methods work for me with `g:mucomplete#enable_auto_at_startup`.

**Comment by mottalrd** [comment]
Wow, thank you @lifepillar ! I'll take a look at your suggestions today

**Comment by mottalrd** [comment]
All works now, this is what I ended up with (and some extra pointers)

```
set completeopt+=menuone
set completeopt+=noselect
set shortmess+=c   " Shut off completion messages
let g:mucomplete#enable_auto_at_startup = 1
" https://github.com/lifepillar/vim-mucomplete/issues/149
" https://medium.com/usevim/set-complete-e76b9f196f0f
let g:mucomplete#chains = { 'default': ['tags', 'incl', 'c-p'] }
```

Thank you!

**Comment by lifepillar** [comment]
If you have `'tags'` and `'incl'` in your completion chain, you should also set:

```vim
set complete-=t
set complete-=i
```

because `'c-p'` by default searches tags and included files, too (`'c-p'` works like Vim's CTRL-P, which uses the sources specified in `'complete'`).

Unless you want aggregated results when you press Shift-Tab (pressing Shift-Tab runs the completion chain backwards, so `'c-p'` is tried first).

**Comment by mottalrd** [comment]
Gotcha, thank you!
