### ISSUE TITLE
`set completeopt+=longest` incompatible with `set spell`

### ISSUE THREAD

**Issue by cwfoo** [lifepillar/vim-mucomplete#150]
### Settings

```vim
set completeopt+=longest,menuone,noselect
let g:mucomplete#enable_auto_at_startup = 1
set spell
```

### Problem

Unable to insert more than 2 letters. For example, I cannot write `orange` because once I type `a` (i.e. the third letter), everything (i.e. `ora`) disappears.

### Observations

If `longest` is removed, I am able to type properly:

```vim
set completeopt+=menuone,noselect
let g:mucomplete#enable_auto_at_startup = 1
set spell
```

### Version information
* Vim 8.0
* vim-mucomplete v1.4.0

**Comment by lifepillar** [comment]
Well, that's expected, and it doesn't depend on MUcomplete. Disable MUcomplete and type `ora<c-x>s` (uses built-in spelling completion). The text you have typed disappears. That is because the completion menu doesn't offer only completions that start with `ora` but also words like `ara` and `era`, and `longest` (see `:help cot`)

>only inserts the longest common text of the matches,

which is the empty prefix in this case. This appears to work with `<c-x>s`:

```vim
set completeopt+=longest,menuone,noinsert
```

but it seems to behave differently in MUcomplete. I will take a look.

**Comment by lifepillar** [comment]
According to `:help cot`, `noinsert` has no effect when `longest` is used. So, this combination is not really supported by MUcomplete, because MUcomplete requires either `noinsert` or `noselect` to be active when autocompletion is on.

As for the combination `noselect` plus `longest`, as I said, it works as advertised (albeit, maybe, not in a useful way). I am not totally opposed to make the behaviour more useful, though, even if it is not compatible with what Vim does. But, what would you expect to happen when you type, say, `ora` and the matches are, say, `ora`, `ara` and `era`, which is different from what would happen without `longest`?

**Comment by cwfoo** [comment]
@lifepillar Thank you for the explanation. It appears that I have misunderstood the default behaviour of `longest` (with or without MUcomplete).

Feel free to close this issue.
