### ISSUE TITLE
How to add the line completion <C-X>L to the results?

### ISSUE THREAD

**Issue by psprint** [lifepillar/vim-mucomplete#182]
Hi,
I've tried:

```vim
let g:mucomplete#user_mappings = { 'keyl' : "\<c-x>l" }
let g:mucomplete#chains = { 'zsh' : ['file', 'keyn', 'keyl'] }
```

However this breaks input – after entering a key it starts repeating `l`s, like so:

```
    return <a key is entered now>0llllllllllllllllllllll
```

**Comment by lifepillar** [comment]
Line completion is supported out of the box with the `"line"` method:

```vim
:let b:mucomplete_chain = ['line']
```

Type:

```
I like biking
I like swimming
I like<Tab>
```

**Comment by psprint** [comment]
It behaves differently than `<C-X><C-L>`, see [asciicast](https://asciinema.org/a/aw0F1uUDyDVuqvhYTxy77BJPM).

**Comment by lifepillar** [comment]
You are not supposed to use `g:mucomplete#user_mappings` to (re)define built-in completion methods. That's not going to work as expected, in general. MUcomplete provides all of them, in a way that takes into account the particular way each one works. So, stick with `'line'` and `'omni'`, for line-completion and omni-completion, respectively.

In your example, the second configuration (using `'line'`) works as expected: since `'keyn'` is before `'line'`, you get keyword completions first. The first configuration (using your own `'keyl'`) does not produce the expected result (and it's not expected to do so as you are mapping a built-in method), because keyword completion should be triggered, not line completion.

If you want line completion to be given a higher priority, put it earlier in the chain, e.g., try:

```vim
:let b:mucomplete_chain= ['file', 'line', 'keyn']
```

As for the lag, you should check your omni-completion function and/or tags completion (which seem the ones that cause a delay in your example). For instance, to test omni-completion, disable MUcomplete auto-completion (`:MUcompleteAutoOff`), then try completing by typing CTRL-X CTRL-O. For tags, try CTRL-X CTRL-]. Are those as slow?

**Comment by psprint** [comment]
Ok, it now works. However, `omni` has a strange side effect: [asciicast](https://asciinema.org/a/64u5C6itNHtL4b3riPh20uF43).

**Comment by psprint** [comment]
One other problem: [asciicast](https://asciinema.org/a/o0QznSwmlnxokIqSERIcQ12Yb).
