### ISSUE TITLE
`C-l` (cycling forward) is shadowed by a standard mapping

### ISSUE THREAD

**Issue by lacygoill** [lifepillar/vim-mucomplete#43]
Hello,

If I write this in `/tmp/vimrc.vim`:
```
set cot=menu,menuone
set rtp+=~/.vim/plugged/vim-mucomplete/
set dictionary=/usr/share/dict/words

let g:mucomplete#chains = {}
let g:mucomplete#chains.default = ['keyn', 'line', 'dict']

" foofoo   word
" foobar   word
" foobaz   word
" foo
```
And if I start Vim like this:

    vim -Nu /tmp/vimrc.vim /tmp/vimrc.vim

I position the cursor on the last line after `foo` and try to complete it by hitting Tab. The pop-up menu appears and gives me suggestions (`foofoo`, `foobar`, `foobaz`). If I hit `C-l` to cycle forward in the chain, the plugin tries the `line method`, which gives me another menu displaying the 3 previous lines. But if I hit `C-l` again, instead of cycling forward again and try the `dict` method, the menu selects the previous entry in the menu (as described in `:h i_^x^l`).

Here's how it looks:    http://imgur.com/a/Donh8

I tried to remap the standard `C-l` to various things, but no matter what I did, when the pop-up menu is visible and after hitting `C-x C-l`, `C-l` always does the same thing, it selects the previous entry in the menu.

For example, I tried to simply disable it, like this:

    ino <expr> <C-l> pumvisible() ? '' : ''

It works except when we open the pop-up menu with `C-x C-l`.

In other words, the behavior of `C-l` is inconsistent, it cycles **forward in the chain** as long as the current method is different than line completion. But it cycles **backward in the menu** as soon as the current method is line completion.

I have no idea how to fix this.

There's another problem, which is not very important because the plugin allows to change the default mappings.

By default, to cycle forward or backward in the chain, we have to hit `C-l` or `C-h`. These keys are very useful by default. They respectively add and delete a character from the current match and the pop-up menu is updated accordingly, as described in `:h popupmenu-keys`:
```

In the first state these keys have a special meaning:
<BS> and CTRL-H   Delete one character, find the matches for the word before
		  the cursor.  This reduces the list of matches, often to one
		  entry, and switches to the second state.
Any non-special character:
		  Stop completion without changing the match and insert the
		  typed character.

In the second and third state these keys have a special meaning:
<BS> and CTRL-H   Delete one character, find the matches for the shorter word
		  before the cursor.  This may find more matches.
CTRL-L		  Add one character from the current match, may reduce the
		  number of matches.
any printable, non-white character:
		  Add this character and reduce the number of matches.
```

As an alternative, we could also define `C-j` and `C-k` to cycle in the chain. Instead of imagining the chain horizontally, one would imagine it vertically. We would lose the ability to insert a digraph while the pop-up menu is visible, but I think the default functions provided by `C-h` and `C-l` are far more important.

I know one could write:

```
ino <silent> <plug>(MUcompleteFwdKey) <c-j>
imap         <c-j>                    <plug>(MUcompleteCycFwd)
ino <silent> <plug>(MUcompleteBwdKey) <c-k>
imap         <c-k>                    <plug>(MUcompleteCycBwd)
```

I just think that `C-j` and `C-k` would be more sensible defaults than `C-h` and `C-l`. Any user which doesn't read the documentation will be surprised to see that the behavior of `C-h` and `C-l` changed.  `C-j` and `C-k` are less obtrusive.

Note that if you were to agree, unfortunately, it wouldn't solve the previous issue, the same problem would occur, but for a different method. Replace `line` with `dict` and we have, again, the exact same issue.

The behavior of `C-k` would also be inconsistent, it would cycle backward in the chain as long as the current method is different than dictionary completion. But it would cycle forward in the menu as soon as the current method is dictionary completion.

**Comment by lifepillar** [comment]
Pressing `<c-smth>` after `<c-x><c-smth>` causes Vim to move through the entries of the pop-up menu. In particular, if you trigger line completion with `<c-x><c-l>`, you may keep typing `<c-l>` to move through the menu entries. This ignores the fact that `<c-l>` is mapped. Ditto for `<c-x><c-k>` and `<c-k>`, which explains why the problem occurs with dictionary completion if you map `<c-k>` instead of `<c-l>`.

I don't recall reading about such “feature” in Vim's documentation. I'll take another look, though.

**Comment by lacygoill** [comment]
I also ask the question on [vi.stackexchange.com](http://vi.stackexchange.com/questions/10553/how-to-remap-c-l-and-c-k-in-insert-mode-even-when-the-pop-up-menu-has-been). I don't know whether I will have an answer, but if I have, I'll post it here.

**Comment by lifepillar** [comment]
After re-reading the docs, I think that that is how it is supposed to work: `<c-x>` enters ctrl-x sub-mode, where several keys are available: `<c-n>`, `<c-l>`, `<c-k>`, etc… So, repeating `<c-l>` is ctrl-x mode works as expected. Also,

>The keys that are valid in CTRL-X mode are not mapped

which explains why µcomplete's mappings are ignored.

I think that there is not much we can do, apart from using keys that are not valid in ctrl-x mode.

**Comment by lifepillar** [comment]
…mmh, no, not so fast. What I've just written doesn't make much sense, because it wouldn't explain why `<c-l>` usually works.

**Comment by lifepillar** [comment]
Ok, the behavior I've described three comments above is clearly documented in the respective commands: see `:h i_CTRL-X_CTRL-L`, `:h i_CTRL-X_CTRL-K`, etc…

As I've said, I don't think there is much that µcomplete can do, short of using different mappings (but which ones?), because, as far as I can tell, those keys cannot be remapped.

**Comment by lacygoill** [comment]
I was hoping some kind of dirty hack like installing a fire-once autocmd which would watch the next key pressed, and if it's `C-l` or `C-k` it would replace it with something like `<plug>(MUcompleteCycFwd)`. Using an event like `InsertCharPre`, or something similar. It's probably overkill though.

I don't like the arrow keys, but `<Left>` and `<Right>` seem the only alternatives. You could also use the meta key (alt-), but usually it's used as a prefix to perform various actions on program windows. For example, I use them to move from a pane to another in tmux...

I'll keep trying to find a solution, and post it here if I find something.

**Comment by lifepillar** [comment]
Ok, I've got this information from the Vim list:

>After c-x c-KEY is hit, say KEY being l, c-KEY is identical to c-n, therefore stays in ctrl-x mode.

Since the keys that are valid in ctrl-x mode are not mapped, there is no straightforward way to solve this issue.

The easiest solution would be to change the cycling mappings to the arrow keys (or to another pair of keys that are *never* used in ctrl-x mode). The arrow keys might not be very welcome by some users.

Hacks like fire-once autocmds or similar are against the philosophy of µcomplete, and overkill for this issue. After all, one may always choose to change the mappings.

RE changing the default keys to `<c-j>/<c-k>`, one drawback is that the `dict` method is in the default chain, so it is more likely that users hit this problem when pressing `<c-k>`.

**Comment by lacygoill** [comment]
Some default methods have drawbacks, the `spel` method for example. To solve this, the plugin re-implements the method in its own and better way. Maybe we could do the same for the `dict` and/or `line` method. If we re-implement the method, then we could get the same results, without facing the current issue.

I could try to work on it and push a PR. What do you think? Is it worth it?

**Comment by lifepillar** [comment]
>Some default methods have drawbacks, the spel method for example. To solve them, the plugin re-implements the method in its own and better way. Maybe we could do the same for the dict and/or line method.

The `uspl` method still relies on Vim's built-in functions, so it is relatively straightforward. The `path` method is kind of an exception (although it is not very complicated), and I hope that it will remain the only one :) Re-implementing the `dict` or `line` methods would likely involve much more code and/or would be inefficient. Such code would need to be maintained, too.

Also, unless all Vim completion methods were re-implemented, shadowed mappings would still be a potential issue, because `<c-h>/<c-l>` might be redefined by some users to conflict with mappings valid in ctrl-x mode.

I think that two things should be done: deciding the most appropriate defaults for cycling keys, and documenting the potential conflicts. So, I'm reopening this.

**Comment by lifepillar** [comment]
Better defaults for cycling might be `<c-h>` and `<c-j>`: no conflicts with ctrl-x mappings, and still on the home row. Losing the original function of `<c-h>` when the pop-up menu is visible is not so dramatic, since you may always use `<bs>` (and most people would do it anyway). @lacygoill What do you think?
