### ISSUE TITLE
Fuzzy completion?

### ISSUE THREAD

**Issue by renstrom** [lifepillar/vim-mucomplete#51]
This is maybe out-of-scope and/or not feasible for vim-mucomplete, but I'm gonna ask anyway. Would it be possible to do fuzzy matching like YCM?

**Comment by lifepillar** [comment]
I'd say no, because to do so would essentially require overriding Vim's built-in mechanisms, which is the opposite of what µcomplete tries to do. MUcomplete might use fuzzy matching if exposed by an omni function (provided that plugins that offer fuzzy omni completions exist), but that would likely be affected by an issue similar to https://github.com/lifepillar/vim-mucomplete/issues/50.

**Comment by renstrom** [comment]
I suspected as much. Anyway, thanks for explaining :)

**Comment by mrbiggfoot** [comment]
It is now possible to have fuzzy search in mucomplete!
Check out my fork of neovim: https://github.com/mrbiggfoot/neovim
