### ISSUE TITLE
Brief flicker when switching chains.

### ISSUE THREAD

**Issue by jordwalke** [lifepillar/vim-mucomplete#62]
First of all thanks for `mucomplete`. It was super easy to configure and get started, and generally does the right thing. Great plugin:

- [ x] I have followed the instructions in `:help mucomplete-troubleshooting`.

My settings:

```
  let g:mucomplete#can_complete = {}
    
  let g:mucomplete#can_complete.default = {'omni': {t -> strlen(&l:omnifunc) > 0  &&  t =~# '\%(\k\|\.\)$' }}
  let g:mucomplete#chains = {
    \ 'default' : ['path', 'omni', 'incl', 'keyn', 'dict', 'uspl', 'ulti'],
    \ 'vim'     : ['path', 'cmd', 'ulti', 'keyn']
    \ }

```

I noticed flickering when `mucomplete` switches between chains.

When the popup has this and is using omnicomplete:

<img width="410" alt="screen shot 2017-04-24 at 3 23 55 pm" src="https://cloud.githubusercontent.com/assets/977348/25361258/134fe18e-2902-11e7-816f-df9e9255288a.png">

And then I hit the next character `a`, which switches from 'omni' to 'incl', it changes to this, but for a brief moment in between there is a flicker.

<img width="255" alt="screen shot 2017-04-24 at 3 24 02 pm" src="https://cloud.githubusercontent.com/assets/977348/25361259/15026326-2902-11e7-9e3f-7b81303ef8e1.png">

**Comment by lifepillar** [comment]
That is unavoidable, I'm afraid. What happens can be simulated without µcomplete: type

```
String.conca<c-x><c-o>a<c-x><c-n>
```

In other words, after `String.conca` omni-completion kicks in, but when you type the next `a` the pop-up menu is closed because there is no match. MUcomplete then tries to complete `concaa`, this time resulting in keyword completion. The flicker is due to the pop-up closing and re-opening (btw, if you have `lazyredraw` on, turning it off may help a bit). In my experience, this is less noticeable in GUI Vim.

What you'd want is a completion method, possibly based on Vim's `complete()`, which collects *both* omni-completion suggestions *and* keyword suggestions in a single menu. For omni-completion, that isn't difficult: you may invoke an omni-completion function directly. But Vim does not expose an interface for keyword completion, so for that you would need to implement an algorithm that collects the current keywords (which, btw, is what YCM and similar plugins do). Something like that goes beyond the scope of µcomplete, although it would make a good idea for a complementary plugin, because the problem is orthogonal to the functionality µcomplete provides (this has been mentioned in past issues as well). In other words, if such a completion function existed, using it with µcomplete would just be a matter of defining a new method with `g:mucomplete#user_mappings`.

**Comment by lifepillar** [comment]
Btw, putting `'keyn'` before `'incl'` in your completion chain  may help alleviate the problem, because `'keyn'` is generally faster. Then, you may type `<c-j>` for those cases when µcomplete suggests local keywords, but you want keywords from included files as well.

**Comment by jordwalke** [comment]
Have you considered having `mucomplete` perform a merge of all the chains into one giant datasource? mucomplete would have complete control.

**Comment by lifepillar** [comment]
Vim does not offer direct support for such a merge, e.g., there is no function that returns all the keywords in the current and included files as a List. That's why I have said that it would be a good idea for a plugin providing a set of completion functions. The thing in Vim that gets closer to your idea is `<c-n>`/<c-p>` (keywords as defined in `'complete'`). One could imagine adding a flag to `'complete'` to include the result of the current omni-completion function.

**Comment by jordwalke** [comment]
Okay, so imagine everything *but* keyword completion. Can mucomplete merge several custom defined completion implementations into one list? (You could see three omnicomplete items along with three ultisnips items at once for example).

**Comment by lifepillar** [comment]
>Can mucomplete merge several custom defined completion implementations into one list?

Currently, it doesn't. I may think about it, though.

**Comment by jordwalke** [comment]
That could be a really cool feature. Right now, it's weird how there will be one entry for the first popup chain, and then when I type more, it goes away and five more pop up for the next chain. It seems all that available space in the first case could be filled with the second chain. I believe this is how many modern IDEs do it.

**Comment by lifepillar** [comment]
@jordwalke @qazip I have created a new *experimental* repo: [vim-ucf](https://github.com/lifepillar/vim-ucf). It doesn't include keyword completion yet (it doesn't include much, really), but you may aggregate omni-completion suggestions and UltiSnips suggestions in one menu by putting this in your `vimrc`:

```vim
let g:mucomplete#user_mappings = {
  \ 'aggr': "\<c-r>=ucf#aggregate#complete()\<cr>"
  \ }

let g:mucomplete#chains = { 'default': ['aggr'] }
```
or this:

```vim
set completefunc=ucf#aggregate#completefunc()
let g:mucomplete#chains = { 'default': ['user'] }
```

(The two snippets should be functionally equivalent.)

If you think that something like that may solve your issues, I may keep working on it.

**Comment by qazip** [comment]
Should I comment my mucomplete config before pasting those or should I just use whatever I have plus those lines?

```
let g:mucomplete#enable_auto_at_startup = 1
set completeopt+=menuone
inoremap <expr>  <cr> mucomplete#popup_exit("\<cr>")
let g:mucomplete#chains = { 'default': [ 'ulti', 'omni', 'keyn', 'incl'] }
set completeopt+=preview
set completeopt+=noselect,noinsert,menu,menuone
set shortmess+=c
```

**Comment by lifepillar** [comment]
No, you may keep your configuration.

**Comment by qazip** [comment]
Doesn't work for me. If I have a "testing.cpp" with "for1", if I type "for", I'll only see the snippets completions. If I type "for1", my cursor will move to the first for1.. Whenever I type a word that's already in the file, my cursor will move to that word/line.

**Comment by lifepillar** [comment]
>If I have a "testing.cpp" with "for1", if I type "for", I'll only see the snippets completions.

You should also see omni-completions. If you turn off µcomplete (`:MUcompleteAutoOff`) and type `for<c-x><c-o>` do you get any completion?

>Whenever I type a word that's already in the file, my cursor will move to that word/line.

I have been able to reproduce that, but not consistently. Do you have an example?

**Comment by qazip** [comment]
> You should also see omni-completions. If you turn off µcomplete (:MUcompleteAutoOff) and type for<c-x><c-o> do you get any completion?

No.

> I have been able to reproduce that, but not consistently. Do you have an example?

If the words are in the same line, it doesn't seem to happen. If the word is in the first line of the document, it doesn't happen. However, if the words are in different lines (and not in the first line), it always happens to me.

**Comment by lifepillar** [comment]
First, make sure that omni-completion works (by turning off µcomplete and trying with `<c-x><c-o>`). Maybe, try with a different file type. Then, you should both see UltiSnips and omni suggestions.

>If the words are in the same line, it doesn't seem to happen. If the word is in the first line of the document, it doesn't happen. However, if the words are in different lines (and not in the first line), it always happens to me.

I'll look into it.

**Comment by qazip** [comment]
Tried with a different fily type (.py) and it didn't work. If I comment the lines regarding vim-ucf, omni-completion works.

**Comment by lifepillar** [comment]
For `cpp`, are you just setting the filetype on a new buffer or editing a file? Also, are you using a completion plugin for C++ (like ClangComplete) or Vim's default? Sometimes, C++ omni-completion does not work in new buffers.

**Comment by lifepillar** [comment]
Regarding the jumpy behaviour, using the other method (setting `completefunc` and using `'user'` in µcomplete's chain) should fix it.

**Comment by qazip** [comment]
Using the other method, gives me 

`Unknown function: youcompleteme#Complete`

I'm opening a new file with the .cpp extension: "nvim testing.cpp".

**Comment by lifepillar** [comment]
Try this command:

```vim
:setlocal completefunc=ucf#aggregate#completefunc
```

after opening a file. Btw, having YCM and µcomplete running together is not a good idea.

**Comment by qazip** [comment]
I don't have YCM. I don't know where that error is coming from, but everything that has to do with YCM is commented out.

**Comment by lifepillar** [comment]
I could reproduce the jumpy behaviour without µcomplete and reported it at https://github.com/vim-jp/vim-cpp/issues/45. Now waiting for feedback.

**Comment by lifepillar** [comment]
RE the jumpy behaviour in cpp buffers, I have opened an issue in Vim repo: https://github.com/vim/vim/issues/2699, as vim-cpp is only for syntax files.

**Comment by lifepillar** [comment]
Closing this because:

- the brief flicker is due to changing the completion method (which requires closing and re-opening the popup menu), so it cannot be avoided;

- providing a completion method that aggregates several sources, although feasible, is out of the scope of, and orthogonal to, µcomplete. I have written [vim-ucf](https://github.com/lifepillar/vim-ucf) as a proof of concept, but currently I have no time to develop it further. If someone writes a completion function that aggregates, say, omni-completion, keyword completion and snippets in the same menu, µcomplete can almost certainly make use of it.

- The jumpy behaviour of the cursor in cpp buffers was due to an incorrect use of a user-completion function (which must be used with `completefunc` and not invoked directly).
