### ISSUE TITLE
Spelling completion cuts off word

### ISSUE THREAD

**Issue by Battleroid** [lifepillar/vim-mucomplete#63]
For bug reports only, please provide the following details:

- [x] I have followed the instructions in `:help mucomplete-troubleshooting`.
- [x] Output of `echo g:mucomplete#chains`: `{'vim': ['path', 'cmd', 'keyn'], 'markdown': ['file', 'spel', 'keyn'], 'default': ['path', 'omni', 'keyn', 'dict', 'uspl']}`
- [x] Output of `setl completeopt`: `completeopt=menu,preview,longest,menuone,noinsert,noselect`
- [x] MUcomplete settings in my `.vimrc`, if any: 

```
autocmd FileType markdown,text setlocal spl=en_us linebreak
set completeopt+=longest,menuone,noinsert,noselect
set shortmess+=c
let g:mucomplete#enable_auto_at_startup = 1
let g:jedi#popup_on_dot = 0
let g:mucomplete#chains = { 'markdown': ['file', 'spel', 'keyn'] }
```

- (`'spel'`) `setl spell? spelllang`: `spell spelllang=en_us`

I've had a weird issue for quite a while now. I use file, spelling and c-n completion with markdown/text files only. However it's practically unusable as half the time in the middle of a word it'll begin completing it and chop off the word midway (see video, I'm terrible at explaining my issue).

Is there anything I've misconfigured or can try to correct this issue?

https://streamable.com/omfrn

**Comment by lifepillar** [comment]
Use `'uspl'`, not `'spel'`. That's explained in `:h mucomplete-spel-complete`.

**Comment by Battleroid** [comment]
Ah, ok. Sorry about that. Thanks a bunch.

**Comment by Battleroid** [comment]
Sorry to reopen, but this actually still occurs, even with my chaining and autocmd removed and just setting spell in a text file I can get halfway through a word and then a suggestion clears my active word.

https://streamable.com/h4xe0

**Comment by lifepillar** [comment]
It should work as expected if you remove `longest` from `completeopt`.

**Comment by Battleroid** [comment]
Ok doke I'll give that a go.

On July 3, 2017 10:26:35 AM EDT, Lifepillar <notifications@github.com> wrote:
>It should work as expected if you remove `longest` from `completeopt`.

-- 
Casey Weed

**Comment by lifepillar** [comment]
Just to be clear, with `longest` you are asking to insert the longest common prefix of the matches of the typed text (btw, `noinsert` is ignored when `longest` is present). Usually, that *extends* the typed text, because matches are exact (hence, they share the typed text as a prefix). But spelling suggestions are approximate matches (e.g., for `fav` you get `far`, `fad`, etc… and also `have`), so the longest common prefix is more often than not the empty string. This is why you have your text deleted.

Vim built-in spelling suggestion (`<c-x>s`) obviously ignores `longest` (but it cannot be used with auto-completion because [it makes the cursor jump](https://github.com/lifepillar/vim-mucomplete/issues/22)). MUcomplete's `'uspl'` method is designed to work with auto-completion. However, it is based on an implementation that cannot bypass `completeopt` settings.

There is an [open issue](https://github.com/vim/vim/issues/1206) in Vim, asking for an option to have `<c-x>s` act only on the word before the cursor, which would make µcomplete's variant unnecessary, but for now the workaround is simply not to use `longest` if you have `'uspl'` in your completion chain.

**Comment by lifepillar** [comment]
>Vim built-in spelling suggestion (`<c-x>s`) obviously ignores `longest`

In fact, that is the case  when `completeopt` contains *both* `longest` and `noinsert` (contradicting Vim's documentation). If `completeopt`only contains `longest` then the option is honoured and the behaviour is no different from using µcomplete's `'uspl`' method.

**Comment by Battleroid** [comment]
Thank you, that worked.

Thank you for the explanation as well, clarifies it for me quite well.
