### ISSUE TITLE
Show completions from neosnippet

### ISSUE THREAD

**Issue by linhvng** [lifepillar/vim-mucomplete#71]
First, thank you for an awesome plugin! 👍 

Reading the document, I learn that this plugin support UltiSnips. Copy-pasting your source code, I get this function below:

```
" Snippets: simple command to list all snippets available
function! NeosnippetComplete(pattern) abort
	let s:cmp = 'stridx(v:val, l:pat)' . '==0'
	let snippets = neosnippet#helpers#get_snippets()
	if empty(snippets)
		return ''
	endif

	let l:snippets = neosnippet#helpers#get_snippets()
	let l:pat = matchstr(getline('.'), '\S\+\%'.col('.').'c')
	let l:pat = a:pattern
	let l:candidates = map(filter(keys(snippets), s:cmp),
				\  '{
				\      "word": v:val,
				\      "menu": "[snip] ". get(snippets[v:val], "description", ""),
				\      "dup" : 1
				\   }')
	if !empty(l:candidates)
		" call complete(col('.') - len(l:pat), l:candidates)
		echo col('.')
		echo len(l:candidates)
		echo l:candidates[0]
	endif
	return ''

endfunction
command! -nargs=1 Snippets call NeosnippetComplete(<q-args>)
```

Using `function` or `dd` as the argument of the function returns information from neosnippet snippets. I'm currently trying to integrate the above function in mucomplete. Could you please point me to a place to start adding more completion method?

Mimicking the structure of Ultisnip, I guess the above method need to go in to: `autoload/mucomplete/neosnippet.vim`?
Then change the name of the function to `mucomplete#neosnippet#complete()`?
Then in `autoload/mucomplete.vim`, add something like: 
`'nsnp': "\<c-r>=mucomplete#neosnippet#complete()\<cr>",` to `s:compl_mappings`?

Please excuse me if any of my questions don't make sense, this is my first time poking into vimscript and vim plugins 😝

**Comment by lifepillar** [comment]
Save this function into `~/.vim/autoload/neosnippet.vim`:

```vim
function! neosnippet#complete() abort
	let l:snippets = neosnippet#helpers#get_snippets()
	if empty(l:snippets)
		return ''
	endif

	let l:pat = matchstr(getline('.'), '\S\+\%'.col('.').'c')
	let l:candidates = map(filter(keys(l:snippets), 'stridx(v:val,l:pat)==0'),
				\  '{
				\      "word": v:val,
				\      "menu": "[neo] ". get(l:snippets[v:val], "description", ""),
				\      "dup" : 1
				\   }')
	if !empty(l:candidates)
		call complete(col('.') - len(l:pat), l:candidates)
	endif
	return ''
endfunction
```

and put this into your `vimrc`:

```vim
let g:mucomplete#user_mappings = { 'neosnippet': "\<c-r>=neosnippet#complete()\<cr>" }
```

Then, you may add the new `'neosnippet'` method to any completion chain. For instance, to have neosnippets enabled in the default chain, put something like this in your `vimrc`:

```vim
let g:mucomplete#chains = { 'default' : ['neosnippet', 'omni', 'keyn'] }
```

I do not recommend messing with µcomplete's code—unless you plan to submit a pull request. But keep in mind that I am not keen to integrate support for other plugins into µcomplete, among the rest because the definition of completion methods like the above is orthogonal to µcomplete's functionality. Support for UltiSnips is an exception (for historical reasons), but some day I might factor that code out into [a complementary plugin](https://github.com/lifepillar/vim-ucf).
