### ISSUE TITLE
Suggestion: auto hide pop up menu if there's a single identical match

### ISSUE THREAD

**Issue by dbmrq** [lifepillar/vim-mucomplete#76]
Here's an example:

<img width="430" alt="captura de tela 2017-12-07 as 21 35 47" src="https://user-images.githubusercontent.com/15813674/33744083-a7fc25a8-db96-11e7-827c-2c53c427d349.png">

In this case there's a single suggestion in the pop up menu and it's identical to the word I've already typed, so it's useless. Also I have completion methods that only show up when I trigger them manually with `<tab>` ([like the thesaurus in the tips](https://github.com/lifepillar/vim-mucomplete/blob/8e1ddf51f47cd5351cb37a622c5eec1c9c6d2130/doc/mucomplete.txt#L538))… so in this case I have to exit the current menu before being able to type `<tab>` and get the thesaurus suggestions. It would be handy if the pop up menu were automatically hidden (or didn't show up at all).

---

Also, a second suggestion: you should add a PayPal donation link to the readme. Great work here. 🍻

**Comment by lifepillar** [comment]
>In this case there's a single suggestion in the pop up menu and it's identical to the word I've already typed, so it's useless. 

To be fair, the suggestion should appear after typing two or three characters (depending on the completion type), so, if your word is longer than that, it's still useful to see the menu, because you may then decide to complete it (or not). For example, if your buffer contains:

```
supercalifragilisticexpialidocious
su
```

the completion menu should show `supercalifragilisticexpialidocious` after typing `su`, which you may then complete, for example, by typing `<tab>`.

MUcomplete requires `menuone`, so what you ask for is not easily achievable. I may try and see whether I can find a solution that does require `menuone`, but I'm afraid that it won't be easy (or possible at all, given how µcomplete works).

>Also I have completion methods that only show up when I trigger them manually with <tab> (like the thesaurus in the tips)… so in this case I have to exit the current menu before being able to type <tab> and get the thesaurus suggestions.

You may use `<c-h>` or `<c-j>` when the pop-up menu is visible to switch the completion chain. You may also configure µcomplete to use `<tab>` and `<s-tab>` to cycle among the different completion methods, if you prefer (see `g:mucomplete#cycle_with_trigger`). Does that help?

>you should add a PayPal donation link to the readme. Great work here.

Ah ah, thanks. I'll think about it :)

**Comment by lifepillar** [comment]
>You may use <c-h> or <c-j> when the pop-up menu is visible to switch the completion chain.

In fact, this would not help in your case because manually activated methods are skipped by default if the pop-up menu has been triggered automatically and not by a key. But I have fixed that: please download the current master and put this in your vimrc:

```vim
let g:mucomplete#cycle_all = 1
```

Now, completion methods that only show up when you trigger them manually will be considered while cycling with CTRL-H or CTRL-J. So, in your example, when you type `word` keyword completion is triggered (showing only one match). If you press CTRL-J, assuming that `'thes'` is listed after `'keyn'` in the current completion chain, you would get a list of synonyms (if there are any). So, you don't need to dismiss the menu to get thesaurus suggestions. Does it make sense?

**Comment by lifepillar** [comment]
Mmh, I was reviewing the code and the history of the project, and, unless I am missing something, the only use case that depends on `menuone` is when you tab-complete a word that admits only one completion: without `menuone`, in that case you don't get the completion (which someone may consider as a bug).

So, you may in fact try to `:set completeopt-=menuone`, and µcomplete should still work fine (with the proviso above).

**Comment by lifepillar** [comment]
And just to be clear, if you are asking for the following behaviour:

1. when you type `wo`, the pop-up menu appears showing the only match (`word`);
2. you continue typing `r` (so now the text before the cursor is `wor`) and the menu stays open;
3. you continue typing `d` (so now the text before the cursor is `word`) and the menu is closed because the only menu entry matches the buffer text;

I don't think that this is possible. Vim does not provide any way, AFAIK, to examine the current content of a pop-up menu. In particular, there is no way for µcomplete to know that the menu is displaying just one entry.

**Comment by dbmrq** [comment]
Yes, that's what I was hoping for.

I thought there was an easy way to get the completion suggestions from Vimscript. Oh, well… the new `g:mucomplete#cycle_all` option is already a huge help, thanks! :)

---

One more suggestion. Vim's thesaurus doesn't allow spaces within its entries. One attempt to work around it is to `set iskeyword+=32`, but it has other side effects, so we have to do `set iskeyword-=32` right after that.

People talk about it [here](https://stackoverflow.com/a/21132116/3539651), [here](http://vim.1045645.n5.nabble.com/Thesaurus-td1195061.html) and [this is my own attempt](https://www.reddit.com/r/vim/comments/55y53e/allow_spaces_in_thesaurus_entries:).

But it would be easy to add `setl isk+=32` to `mucomplete#tab_complete(dir)` or something like that, and then use an autocmd to do `setl isk-=32` right after that.

If you don't want to do that, it would also be nice if you could add a custom event (something like `doautocmd User MUBeforeTab`) before tab completion so I could use it to `set isk` myself.

**Comment by lifepillar** [comment]
Thanks for your feedback, but don't be afraid to open different GitHub issues for each of your issues or feature requests: it makes them easier to track and reference :) I have opened a [new issue](https://github.com/lifepillar/vim-mucomplete/issues/77): let us continue the discussion there.

RE this issue, I am closing it with the following resolution:

1. It is not possible (AFAIK) to get information from Vim about what is displayed in a completion menu, so the requested feature cannot be implemented (at least, not easily);

2. As an approximation, one might remove `menuone` from `completeopt`, with the drawback that, when there is only one match, µcomplete will not offer any completion. Besides, the new `g:mucomplete#cycle_all` option helps mitigate the need for the requested behaviour.

**Comment by andymass** [comment]
I initially passed up this plugin because of this sentence in the readme/doc:
```vim
Mandatory Vim settings:
set completeopt+=menuone
```
From your comments on this issue it seems that this is no longer the case.  Would you be willing to clarify this situation in the readme/doc?

**Comment by lifepillar** [comment]
I don’t know. Making `menuone` only a “recommended” setting does not make much sense. I expect people would start complaining that after `foobar fo` they don’t get any completion. That’s not intuitive.

**Comment by lifepillar** [comment]
>you should add a PayPal donation link to the readme

@dbmrq Finally followed up on this ;)

**Comment by dbmrq** [comment]
@lifepillar For some reason it doesn't let me complete the donation though. Keeps asking for captcha codes or throws generic errors. :/

And I just completed a different purchase using PayPal. I don't know if this is a problem with their donation platform or what.

**Comment by lifepillar** [comment]
@dbmrq Well, thanks for trying! (I don't know what the issue may be.)

**Comment by dbmrq** [comment]
Ha! It wouldn’t work on my desktop for some reason, but it worked on my phone with the mobile website. 🤷🏻‍♂️

Cheers!
